# Generated by Django 2.1.5 on 2019-02-02 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_traffic_offense',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 3, 13, 45, 190720, tzinfo=utc)),
        ),
    ]
