# Generated by Django 2.1.5 on 2019-02-02 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20190202_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_traffic_offense',
            name='remarks',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='db_traffic_offense',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 3, 15, 27, 829118, tzinfo=utc)),
        ),
    ]
