# Generated by Django 2.1.5 on 2019-02-02 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_auto_20190202_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_traffic_offense',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
