# Generated by Django 2.1.5 on 2019-02-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_auto_20190202_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_traffic_offense',
            old_name='timestamp',
            new_name='time_stamp',
        ),
    ]
