# Generated by Django 2.1.5 on 2019-02-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_auto_20190202_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_traffic_offense',
            name='demerit',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='db_traffic_offense',
            name='fine',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='db_traffic_offense',
            name='remarks',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
