# Generated by Django 2.1.5 on 2019-02-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_auto_20190202_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_traffic_offense',
            name='time_stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
