# Generated by Django 2.1.5 on 2019-02-02 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0009_auto_20190202_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_traffic_offense',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
