# Generated by Django 2.1.5 on 2019-02-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0010_auto_20190202_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_case_ongoing',
            name='remarks',
            field=models.CharField(default='', max_length=100),
        ),
    ]
