version: '3'
services:
  db:
    image: postgres:11-alpine
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"

  node:
    build: .
    image: yykcool/lit
    ports:
    - "8000:8080"
    depends_on:
      - db